/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VitalSign;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author grace
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory vsh) {
        initComponents();
        this.history = vsh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblPulse = new javax.swing.JLabel();
        lblConsciousStatus = new javax.swing.JLabel();
        fieldTemperature = new javax.swing.JTextField();
        fieldBloodPressure = new javax.swing.JTextField();
        fieldPulse = new javax.swing.JTextField();
        fieldDate = new javax.swing.JTextField();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel1.setText("Create a Vital Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 180, -1));

        lblDate.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblDate.setText("Date");
        add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        lblTemperature.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblTemperature.setText("Temperature");
        add(lblTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        lblBloodPressure.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblBloodPressure.setText("Blood Pressure");
        add(lblBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        lblPulse.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblPulse.setText("Pulse");
        add(lblPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        lblConsciousStatus.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblConsciousStatus.setText("Conscious Status");
        add(lblConsciousStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, -1));

        fieldTemperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTemperatureActionPerformed(evt);
            }
        });
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 150, -1));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, -1));
        add(fieldPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, -1));
        add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 150, -1));

        buttonGroup1.add(btnYes);
        btnYes.setSelected(true);
        btnYes.setText("Yes");
        add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        buttonGroup1.add(btnNo);
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        btnSave.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTemperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTemperatureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTemperatureActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String date = fieldDate.getText();
        float temp = Float.parseFloat(fieldTemperature.getText());
        double bp = Double.parseDouble(fieldBloodPressure.getText());
        int pulse = Integer.parseInt(fieldPulse.getText());
        boolean isConscious;
        
        if(btnYes.isSelected()){
        isConscious = true;
        }else{
        isConscious = false;
        }
        
        VitalSign vs = new VitalSign();
        vs.setDate(date);
        vs.setTemperature(temp);
        vs.setBloodPressure(bp);
        vs.setPulse(pulse);
        vs.setIsConscious(isConscious);
        
        //setting success pop-up message
   JOptionPane.showMessageDialog(this,"Successfully saved", "Success",JOptionPane.INFORMATION_MESSAGE);
   
   fieldDate.setText("");
    fieldTemperature.setText("");
    fieldBloodPressure.setText("");
    fieldPulse.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldDate;
    private javax.swing.JTextField fieldPulse;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblConsciousStatus;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPulse;
    private javax.swing.JLabel lblTemperature;
    // End of variables declaration//GEN-END:variables
}
