/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Account;
import Model.AccountDirectory;
import java.awt.CardLayout;

/**
 *
 * @author grace
 */
public class MainJFrame extends javax.swing.JFrame {

    private AccountDirectory accountDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.accountDirectory = new AccountDirectory();
        generateDemoData();
        
    }
    
    private void generateDemoData() {
        
    Account newAccount = accountDirectory.addAccount();
    newAccount.setAccountNumber("444444444");
    newAccount.setRoutingNumber("001122334");
    newAccount.setBankName("Bank of America");
    newAccount.setBalance(200);
    
    Account anotherNewAccount = accountDirectory.addAccount();
    anotherNewAccount.setAccountNumber("555555555");
    anotherNewAccount.setRoutingNumber("007711234");
    anotherNewAccount.setBankName("Santander Bank");
    anotherNewAccount.setBalance(1200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        topjPanel1 = new javax.swing.JPanel();
        btnAccountingMng = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnAccountingMng.setBackground(new java.awt.Color(204, 255, 255));
        btnAccountingMng.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAccountingMng.setText("Open Account Manager Work Area");
        btnAccountingMng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountingMngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topjPanel1Layout = new javax.swing.GroupLayout(topjPanel1);
        topjPanel1.setLayout(topjPanel1Layout);
        topjPanel1Layout.setHorizontalGroup(
            topjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topjPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnAccountingMng)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        topjPanel1Layout.setVerticalGroup(
            topjPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topjPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnAccountingMng)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jSplitPane2.setTopComponent(topjPanel1);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccountingMngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountingMngActionPerformed
        // TODO add your handling code here:
        AccountMngWorkAreaJPanel panel = new AccountMngWorkAreaJPanel(userProcessContainer,accountDirectory);
        userProcessContainer.add("AccountMngWorkAreaJPanel", panel);
    
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAccountingMngActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountingMng;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel topjPanel1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    
}
